# Generated by Django 3.1.3 on 2021-03-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('authors', models.TextField(max_length=200)),
                ('year', models.IntegerField()),
                ('form', models.TextField(choices=[('F1', 'Form 1'), ('F2', 'Form 2')])),
                ('language', models.TextField(choices=[('EN', 'English'), ('DE', 'German')])),
                ('region', models.TextField(choices=[('R1', 'Region 1'), ('R2', 'Region 2')])),
                ('tags', models.TextField()),
            ],
        ),
    ]
