# Generated by Django 3.1.3 on 2021-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mark',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
