# Generated by Django 3.1.3 on 2021-03-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mark',
        ),
    ]
