# Generated by Django 3.1.3 on 2021-03-23 07:12

import articles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=articles.models.CommaSepField(default='default'),
            preserve_default=False,
        ),
    ]
